services:
  - type: worker
    name: apniincomebot
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python apni_income_bot.py"
    pythonVersion:Â 3.10.13
